### ISSUE TITLE
The option not to create plugconf when 'volt get'

### ISSUE THREAD

**Issue by tyru** [vim-volt/volt#148]
The following config disables creating skeleton plugconf on `volt get`.

```toml
[get]
create_skeleton_plugconf = false
```
