### ISSUE TITLE
[volt build] Put all scripts into single path in Vim runtimepath

### ISSUE THREAD

**Issue by tyru** [vim-volt/volt#170]
In config.toml

```toml
[build]

# Add "single_plugin" to strategy.
# If you specify it, `volt build` puts all scripts into the specified path
strategy = "single_plugin"

# When strategy is "single_plugin": Destination plugin directory.
# You put the path to 'runtimepath' in your vimrc (if not in default)
# It is handy to specify default 'runtimepath' directory or pack directory
# because you don't have to add the path to 'runtimepath' in vimrc.
destination = "$HOME/.vim"
destination = "$HOME/.vim/pack/bundled"

# When strategy is "single_plugin": The action when the paths of vim script files are conflicted.
# * "error" (default): Report error and exit.
# * "continue_same": Check conflicted files contents, and if the contents of all files
#                                which have same paths are same, copy one of the files and continue.
single_plugin_on_conflict = "continue_same"

# Exclude pattern. This pattern format is same as gitignore.
exclude = ["/*.md"]  # ignore the *.md files on the top of repository
```
